# Generated by Django 2.0.2 on 2018-04-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('gif', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'User_text',
                'verbose_name_plural': 'User_texts',
            },
        ),
    ]
